language: node_js
node_js:
  - node
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libpcap-dev
      - libssl-dev
      - cmake
      - libboost-all-dev
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
before_install:
  - ./etc/scripts/build-deps
install:
  - npm run install-local
