language: node_js

node_js:
  - node
  - iojs
  - '4'
  - '3'
  - '2'
  - '1.8'
  - '1.0'

os:
  - linux
  - osx

before_install:
  - env | sort
  - ./etc/scripts/build-deps
  - export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
