language: node_js

node_js:
  - "0.10"
  - "0.11"

os:
  - linux
  - osx

before_install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; sudo apt-get install libpcap-dev libssl-dev cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi
  - sh scripts/install_libtins.sh
  - LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
