language: node_js

node_js:
  - "0.10"

os:
  - linux
  - osx

before_install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libpcap-dev; fi
  - npm install
