language: node_js

node_js:
  - "0.10"
  - "0.11"

os:
  - linux
  - osx

before_install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh scripts/install_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sh scripts/install_osx.sh; fi
