language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

os:
  - linux
  - osx

before_install:
  - env | sort
  - sh "scripts/setup_${TRAVIS_OS_NAME}.sh"
  - sh scripts/install_libtins.sh
  - export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
