language: node_js
node_js:
  - node
  - iojs
  - '4'
  - '3'
  - '2'
  - '1.8'
  - '1.0'
  - '0.12'
  - '0.11'
env:
  global:
    - CPLUS_INCLUDE_PATH="$(pwd)/etc/deps/libtins/include:$(pwd)/etc/deps/avro/lang/c++/build/include:/usr/local/include"
    - LIBRARY_PATH="$(pwd)/etc/deps/libtins/build/lib:$(pwd)/etc/deps/avro/lang/c++/build:/usr/local/lib"
before_install:
  - ./etc/scripts/build-deps
