language: node_js
node_js:
  - node
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8
      - libboost-all-dev
      - libpcap-dev
      - libssl-dev
env:
  global:
    - CXX=g++-4.8
install:
  - npm run install-all
