language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - libpcap-dev
      - libssl-dev
      - cmake
      - libboost-all-dev
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
    - CPLUS_INCLUDE_PATH="$(pwd)/etc/deps/libtins/include:$(pwd)/etc/deps/avro/lang/c++/build/include:/usr/local/include"
    - LIBRARY_PATH="$(pwd)/etc/deps/libtins/build/lib:$(pwd)/etc/deps/avro/lang/c++/build:/usr/local/lib"
before_install:
  - ./etc/scripts/build-deps
