language: node_js
node_js:
  - node
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8
      - libboost-all-dev
      - libpcap-dev
      - libssl-dev
env:
  global:
    - CXX=g++-4.8
    - LD_LIBRARY_PATH="$(pwd)/etc/deps/libtins/build/lib:$(pwd)/etc/deps/avro/lang/c++/build:/usr/local/lib"
install:
  - npm run install-all
